name: Deploy

on:
  workflow_run:
    workflows: ["Publish"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    name: Production deployment
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Update API instance
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ./services/api
            docker compose pull api
            docker compose down api
            docker compose up api --detach
            docker image prune --force
